### PR TITLE
Update ElastiCache CodeGen test based on new SDK

### PR DESCRIPTION
**Pull request by nmvk**
ElastiCache would use new AWS SDK Go to include new features like LogDelivery which are currently not part of `elasticache-controller`. This PR updates the test data used in code generator for Elasticache tests.

Additionally I have updated `generator.yaml` to be inline with one being used in `elasticache-controller`. Updated unit tests which use `CacheCluster` resource to `ReplicationGroup`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jaypipes** [comment]
@nmvk no changes to the sdk.go generation?

**Comment by A-Hilaly** [comment]
@nmvk what changes does this version bring exactly? This repository is using `aws/aws-sdk-go` for it `private/model` package.
If you need this version for `elasticache-controller` code generation you can set it using `AWS_SDK_GO_VERSION` env variable

**Comment by nmvk** [comment]
Thanks @jaypipes @A-Hilaly I got confused about the usage of the `aws-sdk-go` in this project. I originally thought our tests used them. I have updated the PR with ElastiCache specific change.

**Comment by A-Hilaly** [comment]
Thanks! Yes i agree that it is a bit confusing :)

**Review by A-Hilaly — APPROVED** [review]
:+1:

**Pull request merged**
