### PR TITLE
feat(crossplane): Add context to isUpToDate and return diff

### PR DESCRIPTION
**Pull request by MisterMX**
Description of changes:

This adds a `context.Context` parameter to the `isUpToDate` function in the Crossplane controller template.

Required for https://github.com/crossplane-contrib/provider-aws/issues/1828.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by chlunde** [comment]
@jaypipes as a maintainer of crossplane-community/provider-aws, I approve this PR. It would be nice to have it merged. We could also consider moving the templates into provider-aws if we have/get support for external templates, so we don't have to bother you on changes like this.

**Review by jaypipes — APPROVED** [review]
Thank you @MisterMX, apologies for the delayed review!

**Review by a-hilaly — APPROVED** [review]
:+1:
/lgtm
/ok-to-test

**Comment by a-hilaly** [comment]
Manually merging as the errors mentioned in the log are not representative of real errors

**Pull request merged**
