### PR TITLE
Add sdk addon hook

### PR DESCRIPTION
**Pull request by kumargauravsharma**
Issue #, if available:

Ability for service controllers to add code (additional functions, variables etc as needed) to sdk.go file using hooks as extension mechanism.

Description of changes:

This PR adds `sdk_addon` hook to `sdk.go.tpl`. Using this hook, service controllers can append code to a custom resource's `sdk.go` file. It will help in placing reusable code/functions which are generated dynamically using hook templates.

Following PR contains changes showcasing how this facility helps service controllers auto generate reusable code: https://github.com/aws-controllers-k8s/elasticache-controller/pull/36

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kumargauravsharma** [comment]
> Maybe we can optionally generate a `sdk_addons.go` files?

I think it would complicate the code generator implementation as it would need to decide if this file needs to be generated or skipped.
Currently, the list of files for CR is a fixed list: [code reference](https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/ack/controller.go#L151-L159)

**Review by jaypipes — CHANGES_REQUESTED** [review]
Two things I'm requesting:

1) Let's call this `sdk_file_end` instead of `sdk_addon` please. The reason is twofold: all the other hook points describe where in the file or code flow they are. Secondly, the term "addon" [means something specififc in Kubernetes-speak](https://kubernetes.io/docs/concepts/cluster-administration/addons/) so I want to avoid confusion with that.

2) Please add a callout to this new hook point in the docstring right below here:

https://github.com/aws-controllers-k8s/code-generator/blob/c77aa9c75d944952dee198029ba9822691cd82b0/pkg/generate/ack/hook.go#L58

That basically states `sdk_file_end` is a generic hook point that occurs outside the scope of any specific `AWSResourceManager` method and can be used to place commonly-generated code inside the `sdk.go` file.

Thank you @kumargauravsharma!

**Comment by kumargauravsharma** [comment]
Thanks @jaypipes for your comments.
I have updated the code files per the comments.

**Review by jaypipes — APPROVED** [review]
Sweet. :+1:

**Pull request merged**
