### PR TITLE
aws-sdk-go version bump, 1.37.10 -> 1.42.0

### PR DESCRIPTION
**Pull request by smcavallo**
Signed-off-by: smcavallo <smcavallo@hotmail.com>

Issue #1059, if available:
https://github.com/aws-controllers-k8s/community/issues/1059

Description of changes:
aws-sdk-go version bump, 1.37.10 -> 1.42.0 to unblock crossplane

This will also require a new version of the runtime.
See - https://github.com/aws-controllers-k8s/runtime/pull/60
Leaving this in draft status until there is a new runtime version based on this version of the sdk

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by haarchri** [comment]
any updates here ? In crossplane we have a few requests and needs for 1.42.x

**Comment by vijtrip2** [comment]
@haarchri , Thanks for surfacing this.
I am looking into updating dependencies in ACK core libraries due to security vulnerabilities. Once that is done, I will look into updating aws-sdk-go dependency as well and see which controller breaks.
You can track this issue for progress for now. https://github.com/aws-controllers-k8s/community/issues/1112

-----

FWIW, ACK core team also has plans to automate the testing of aws-sdk-go upgrades in near future, while will help with these upgrades and stay consistent with upstream releases.

**Comment by vijtrip2** [comment]
Closing in favor of upgrade to v1.42.35

**Pull request closed without merging**
