### PR TITLE
add feature gates support in Helm templates

### PR DESCRIPTION
**Pull request by eadasiak**
Issue #, if available: N/A, but related to https://github.com/aws-controllers-k8s/runtime/pull/151

Description of changes: Adds optional support for feature gates in Helm templates.  A top-level key of `featureGates` has been added to the default values file template, and the optional command-line argument has been appended to the deployment template.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by acornett21** [comment]
I'm not sure if the intent is two PR's, one for helm and one for manifests, but my personal preference is to see any flags added to the runtime, to be in one PR in the code-gen for all deployment types.

**Comment by acornett21** [comment]
All tests fail for the same reason

```
Error: INSTALLATION FAILED: parse error at (apigatewayv2-chart/templates/deployment.yaml:199): unexpected EOF
```

so whatever is rendered out for the deployment is incorrect.

**Comment by eadasiak** [comment]
I think I see the issue -- an artifact from local testing.  Will submit a revision in just a sec...

**Review by a-hilaly — APPROVED** [review]
Thank you so much @eadasiak !!

Tested locally with a dry run helm using:
```yaml
featureGates:
  ReadOnlyResources: true
  FeatureXYZ: false
```

Works like a charm~

**Pull request merged**
