### PR TITLE
update aws-sdk-go dependency to `v1.44.93`

### PR DESCRIPTION
**Pull request by brycahta**
Issue #, if available: N/A

Description of changes: 
* update aws-sdk-go dependency to `v1.44.93` and `go mod tidy`
* related runtime PR: https://github.com/aws-controllers-k8s/runtime/pull/102

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brycahta** [comment]
All tests are passing, but the job fails with the same error for all controllers:

`Error: INSTALLATION FAILED: YAML parse error on $CONTROLLER-chart/templates/cluster-role-controller.yaml: error converting YAML to JSON: yaml: line 8: did not find expected key`

**Comment by brycahta** [comment]
Not seeing these tests pass in the last couple code-generator PRs. @RedbackThomson @A-Hilaly  are these tests failing a known issue?

**Comment by A-Hilaly** [comment]
Hey @brycahta , no this is the first time i see a similar issue. Will investigate this.

**Pull request merged**
