### PR TITLE
add NAT to initialisms

### PR DESCRIPTION
**Pull request by brycahta**
Issue #, if available: N/A

Description of changes:
* Adds `NAT` to initialism with preventions

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brycahta** [comment]
Grep'd _aws-sdk-go/models/apis_ to confirm prevention rule:

```
> grep -r '[a-zA-Z]*Nat[a-zA-Z]*' -o . | sort | uniq

./amplifybackend/2020-08-11/api-2.json:NativeClientId
./amplifybackend/2020-08-11/docs-2.json:NativeClientId
./codeguru-reviewer/2019-09-19/api-2.json:NativeS
./comprehendmedical/2018-10-30/docs-2.json:National
./config/2014-11-12/api-2.json:NatGateway
./dms/2016-01-01/docs-2.json:Native
./ec2/2016-11-15/api-2.json:CreateNatGateway
./ec2/2016-11-15/api-2.json:CreateNatGatewayRequest
./ec2/2016-11-15/api-2.json:CreateNatGatewayResult
./ec2/2016-11-15/api-2.json:DeleteNatGateway
./ec2/2016-11-15/api-2.json:DeleteNatGatewayRequest
./ec2/2016-11-15/api-2.json:DeleteNatGatewayResult
./ec2/2016-11-15/api-2.json:DescribeNatGateways
./ec2/2016-11-15/api-2.json:DescribeNatGatewaysMaxResults
./ec2/2016-11-15/api-2.json:DescribeNatGatewaysRequest
./ec2/2016-11-15/api-2.json:DescribeNatGatewaysResult
./ec2/2016-11-15/api-2.json:NatGateway
./ec2/2016-11-15/api-2.json:NatGatewayAddress
./ec2/2016-11-15/api-2.json:NatGatewayAddressList
./ec2/2016-11-15/api-2.json:NatGatewayAddresses
./ec2/2016-11-15/api-2.json:NatGatewayId
./ec2/2016-11-15/api-2.json:NatGatewayIdStringList
./ec2/2016-11-15/api-2.json:NatGatewayIds
./ec2/2016-11-15/api-2.json:NatGatewayList
./ec2/2016-11-15/api-2.json:NatGatewayState
./ec2/2016-11-15/api-2.json:NatGateways
./ec2/2016-11-15/docs-2.json:CreateNatGateway
./ec2/2016-11-15/docs-2.json:CreateNatGatewayRequest
./ec2/2016-11-15/docs-2.json:CreateNatGatewayResult
./ec2/2016-11-15/docs-2.json:DeleteNatGateway
./ec2/2016-11-15/docs-2.json:DeleteNatGatewayRequest
./ec2/2016-11-15/docs-2.json:DeleteNatGatewayResult
./ec2/2016-11-15/docs-2.json:DescribeNatGateways
./ec2/2016-11-15/docs-2.json:DescribeNatGatewaysMaxResults
./ec2/2016-11-15/docs-2.json:DescribeNatGatewaysRequest
./ec2/2016-11-15/docs-2.json:DescribeNatGatewaysResult
./ec2/2016-11-15/docs-2.json:NatGateway
./ec2/2016-11-15/docs-2.json:NatGatewayAddress
./ec2/2016-11-15/docs-2.json:NatGatewayAddressList
./ec2/2016-11-15/docs-2.json:NatGatewayId
./ec2/2016-11-15/docs-2.json:NatGatewayIdStringList
./ec2/2016-11-15/docs-2.json:NatGatewayList
./ec2/2016-11-15/docs-2.json:NatGatewayState
./ec2/2016-11-15/examples-1.json:CreateNatGateway
./ec2/2016-11-15/examples-1.json:DeleteNatGateway
./ec2/2016-11-15/examples-1.json:DescribeNatGateways
./ec2/2016-11-15/examples-1.json:NatGateway
./ec2/2016-11-15/examples-1.json:NatGatewayAddresses
./ec2/2016-11-15/examples-1.json:NatGatewayId
./ec2/2016-11-15/examples-1.json:NatGateways
./ec2/2016-11-15/paginators-1.json:DescribeNatGateways
./ec2/2016-11-15/paginators-1.json:NatGateways
./ec2/2016-11-15/waiters-2.json:DescribeNatGateways
./ec2/2016-11-15/waiters-2.json:NatGatewayAvailable
./ec2/2016-11-15/waiters-2.json:NatGatewayNotFound
./ec2/2016-11-15/waiters-2.json:NatGateways
./medialive/2017-10-14/docs-2.json:Native
./pinpoint/2016-12-01/api-2.json:CleansedPhoneNumberNational
./pinpoint/2016-12-01/docs-2.json:CleansedPhoneNumberNational
./rds/2014-10-31/api-2.json:ActivityStreamEngineNativeAuditFieldsIncluded
./rds/2014-10-31/api-2.json:EngineNativeAuditFieldsIncluded
./rds/2014-10-31/docs-2.json:ActivityStreamEngineNativeAuditFieldsIncluded
./rds/2014-10-31/docs-2.json:EngineNativeAuditFieldsIncluded
./ssm/2014-11-06/docs-2.json:Native
NatGateway
NatGatewayAddresses
NatGatewayId
NatGatewayIds
NatGateways

```

**Review by jaypipes — APPROVED** [review]
:+1:

**Comment by jaypipes** [comment]
Thanks for checking on the current APIs and resource fields, @brycahta.

**Pull request merged**
