### PR TITLE
Refactor model package to use `Config` accessors

### PR DESCRIPTION
**Pull request by brycahta**
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1184 (task 2; migrating access)

Description of changes:
* copy methods accessing `ackgenconfig` from model package to config package
* update methods in model package to leverage `ackgenconfig` accessors instead of directly accessing config
* align `ackgenconfig` accessors with config types (i.e. methods accessing `c.Resources` go in `pkg/config/resource.go`)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
:+1: makes sense to me, nice work @brycahta. In a future commit, I believe we'll want to standardize the method names to use `GetXXX` as a consistent accessor method name, yes?

**Comment by brycahta** [comment]
> 👍 makes sense to me, nice work @brycahta. In a future commit, I believe we'll want to standardize the method names to use `GetXXX` as a consistent accessor method name, yes?

That's correct @jaypipes; working on that PR now.

**Review by A-Hilaly — APPROVED** [review]
Awesome!

**Pull request merged**
