### PR TITLE
Add `IPAM` and `TPM` to initialisms

### PR DESCRIPTION
**Pull request by brycahta**
Issue #, if available: N/A

Description of changes: adds IPAM (IP Address Management) and TPM (Trusted Platform Module) to initialisms

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by brycahta** [comment]
@A-Hilaly is `s3-controller-test` failure still expected? I know we discussed a couple days ago for this PR: https://github.com/aws-controllers-k8s/code-generator/pull/364 For reference:
* [s3 job history](https://prow.ack.aws.dev/job-history/s3/ack-prow-logs/pr-logs/directory/s3-controller-test)

**Review by jaypipes — APPROVED** [review]
muy bueno.

**Comment by jaypipes** [comment]
s3-controller test failure unrelated to this particular PR... merging as-is.

**Comment by A-Hilaly** [comment]
>@A-Hilaly is s3-controller-test failure still expected? I know we discussed a couple days ago for this PR: https://github.com/aws-controllers-k8s/code-generator/pull/364 For reference:

Yes i'm aware of these errors, i need to update s3 package in a seperate PR.

**Comment by A-Hilaly** [comment]
nit: @brycahta We should also port these changes to github.com/aws-controllers-k8s/pkg. I can take care of this task once we starting importing this package from github.com/aws-controllers-k8s/pkg

**Pull request merged**
