### PR TITLE
Import `names` package from `github.com/aws-controllers-k8s/pkg`

### PR DESCRIPTION
**Pull request by A-Hilaly**
Issue #, if available:

Description of changes:
- Import `names` package from `github.com/aws-controllers-k8s/pkg`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by A-Hilaly** [comment]
Awaiting on https://github.com/aws-controllers-k8s/pkg/pull/6#discussion_r972413715

/hold

**Review by jaypipes — APPROVED** [review]
bueno. will be even more bueno once we do proper semver releases of `pkg/` repository

**Comment by A-Hilaly** [comment]
Thank you for the review @jaypipes . If you have a moment could you take a look at https://github.com/aws-controllers-k8s/pkg/pull/6#discussion_r972413715

**Comment by RedbackThomson** [comment]
Is this still a viable PR? @A-Hilaly @jaypipes I know we still have duplication

**Comment by jaypipes** [comment]
> Is this still a viable PR? @A-Hilaly @jaypipes I know we still have duplication

should be after a rebase, yeah.

**Review by jaypipes — APPROVED** [review]
:+1: 

Next step: semver release the `pkg/` repo :)

**Comment by A-Hilaly** [comment]
PR Rebased and tests are passing now. PTAL @jaypipes @jljaco @RedbackThomson 
Before doing make a semver release for ack/pkg I would to add a few new initialisms to the names list (in a seperate PR)
/hold cancel

**Review by jaypipes — APPROVED** [review]
Still :+1: from me.

**Review by jaypipes — APPROVED** [review]
Yes please :)

**Comment by RedbackThomson** [comment]
Let's do it
/lgtm

**Pull request merged**
