### PR TITLE
add ServicePackageName to ack-user-config and ack-user secrets

### PR DESCRIPTION
**Pull request by acornett21**
Issue #, if available:
- Fixes: aws-controllers-k8s/community#1149

Description of changes:
Add in support for service specific configmaps and secret so that a cluster admin can configure each service differently, or the same if they so choose.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Signed-off-by: Adam D. Cornett <adc@redhat.com>

### CODE REVIEW

**Comment by komish** [comment]
This seems reasonable enough. It does, however, mean that administrators who want the same configuration for all installed controllers would effectively have to duplicate configmaps and secrets, right? Was there a user request requesting the feature? 

Either way, this looks like it should accomplish this and seems useful 👍

**Comment by RedbackThomson** [comment]
> This seems reasonable enough. It does, however, mean that administrators who want the same configuration for all installed controllers would effectively have to duplicate configmaps and secrets, right? Was there a user request requesting the feature?
> 
> Either way, this looks like it should accomplish this and seems useful 👍

The current method means that you cannot install multiple controllers with separate permissions, though - which is arguably a larger security concern. I think this PR does a good job of trading off that security concern for your ease of use concern.

**Comment by acornett21** [comment]
> This seems reasonable enough. It does, however, mean that administrators who want the same configuration for all installed controllers would effectively have to duplicate configmaps and secrets, right? Was there a user request requesting the feature?

Yeah you are correct, it's a trade off, they would need to duplicate if they wanted the same configuration. And yes, this granularity was asked for by a user int he Kube slack channel.

**Review by jaypipes — APPROVED** [review]
:+1: doh, sorry for the delay in review/merge @acornett21!

**Pull request merged**
